### ISSUE TITLE
Links to directory index are not properly generated

### ISSUE THREAD

**Issue by wailmerpailmer** [WnP/vimwiki_markdown#1]
When using links in vimwiki, one can specify links as such:

`[Dir](Dir/)`

Using vimwiki, one can specify that that link be interpreted as Dir/index.html or any arbitrary setting using the following:

`let g:vimwiki_dir_link='index'`

The current behavior makes it such that navigating to a directory via the generated HTML files does not work unless the user manually specifies `[Dir](Dir/index.html)` for each link.

Perhaps vimwiki_markdown should check what this variable is set to and replace links to directories such as above with `Dir/index.html` when appropriate?

**Comment by WnP** [comment]
Hi @wailmerpailmer, Thanks for reporting this issue, I'll try to find an elegante way to handle that.

If you've got some idea fell free to share or open a PR.

I'll keep you in touch

**Comment by WnP** [comment]
Hi @wailmerpailmer I've just released [v0.3.0](https://pypi.org/project/vimwiki-markdown/0.3.0/) which provide [your requested feature](https://github.com/WnP/vimwiki_markdown/commit/ce2cc10e71b61dd6776f88a8f98afabedc7adbda).

Let me know if it fits your needs
