### ISSUE TITLE
VimWiki link not supported in HTML conversion

### ISSUE THREAD

**Issue by itsdawei** [WnP/vimwiki_markdown#11]
*I'm not sure if this is a bug or just a non-supported feature.*

I am organizing my VimWiki using built-in VimWiki links using double brackets (i.e. [[index.md]]). However, it doesn't seem to work.

For example, I have the following:
![image](https://user-images.githubusercontent.com/54293336/101266207-e454f480-37a0-11eb-8cda-bccf86b42342.png)
which converts to the following:
![image](https://user-images.githubusercontent.com/54293336/101266322-dd7ab180-37a1-11eb-95ec-32b1e9a741a6.png)

Not sure if this is intended, but it would be nice if the conversion handled this and automatically links to the target file/webpage. This would allow creating the main HTML page that can be navigated to other subpages - much like how a website is actually stuctured.

A **workaround** that I found is replacing the wiki link with the absolute path of the target file using the markdown link syntax, such as \[swift\](~/vimwiki/swift/index.md). This will create a hyperlink in the HTML file and allow navigation between files in your system.

Not sure if this is a necessary feature, but just thought it might be interesting to be able to link to other HTML files in your system. :)

**Comment by WnP** [comment]
Actually if your markdown file reside inside your `vimwiki` folder you can reference it using the following syntax:

```md
[swift](swift/index)
```

No need to expand the whole path. I personally use this syntax for my own wiki index.

Mixing `vimwiki` and `markdown` syntax is not supported, also, imho, I don't think it's a good practice.

**Comment by itsdawei** [comment]
Oh, I didn't realize that the double brackets are exclusive `vimwiki` syntax. My bad. I will try what you are suggesting. Thanks

**Comment by itsdawei** [comment]
It works perfectly! Thanks.

A problem that I had was that i accidentally wrote:
```
[swift](/swfit/index)
```
rather than:
```
[swift](swift/index)
```
The latter syntax works with link redirection in the HTML page, while the former doesn't.
