### ISSUE TITLE
Enable other extensions

### ISSUE THREAD

**Issue by danielb2** [WnP/vimwiki_markdown#2]
great convert. Is there anyway you can enable the table extension as well ?

**Comment by WnP** [comment]
good idea, this extension is now part of the default available extension, see https://github.com/WnP/vimwiki_markdown/commit/7fe889ca927a92d6d9005ad5b81757f4c0112660 for implementation.

You can also set other extensions using the newly created environment variable, see [the markdwon extensions README section](https://github.com/WnP/vimwiki_markdown#markdown-extensions).

Thx

**Comment by WnP** [comment]
@danielb2 feel free to re-open this issue if it doesn't fit your needs.

**Comment by danielb2** [comment]
awesome!  It's exactly what I wanted. Thank you ☺️
