### ISSUE TITLE
How to use vimwiki_markdown under windows 10?

### ISSUE THREAD

**Issue by VimWei** [WnP/vimwiki_markdown#7]
- [x] What I want?

Batch convert vimwiki Markdown files to HTML.

- [x] the output of `:VimwikiShowVersion`.

Os: Windows
Vim: 802
Branch: HEAD
Revision: c9e6afe
Date: 2020-05-26 23:09:58 +0200

- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`

    Plug 'vimwiki/vimwiki', { 'commit': 'c9e6afe' }

    " def wiki dict for normal
    let wiki = {}
    let wiki.name = 'ChenWei VimwikiMd'
    let wiki.path = 'd:/WeirdData/VimwikiMd/'
    let wiki.ext = '.md'
    let wiki.syntax = 'markdown'
    let wiki.nested_syntaxes = {'python': 'python'}
    let wiki.links_space_char = '_'
    let wiki.list_margin = 0
    let wiki.auto_toc = 1
    let wiki.auto_tags = 1
    let wiki.auto_generate_tags = 1

    " dev wiki dict for convert markdown to html
    let wiki.template_path = 'd:/WeirdData/VimwikiMd/templates/'
    let wiki.template_default = 'default'
    let wiki.path_html = 'd:/WeirdData/VimwikiMd/site_html/'
    let wiki.custom_wiki2html = 'vimwiki_markdown'
    let wiki.template_ext = '.tpl'

    " def vimwiki_list and so on.
    let g:vimwiki_list = [wiki]
    let g:vimwiki_ext2syntax = {'.md': 'markdown'}
    let g:vimwiki_global_ext = 1
    let g:vimwiki_autowriteall = 1
    let g:vimwiki_auto_chdir = 1
    let g:vimwiki_folding = 'expr'

- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.

1. Install vimwiki_markdown  `pip install vimwiki-markdown`
2. Config vimrc.
3. Open my vimwiki index file `<leader>ww`
4. Run Convert command `<leader>wh`
5.  The output files in folder `d:\WeirdData\VimwikiMD\site_html\` are only `style.css` but no any HTML files.
and there are some messages:

```
Traceback (most recent call last):^@  File "c:\users\chenwei\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main^@    "__main__", mod_spec)^@  File "c:\users\chenwei\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code^@    exec(code, run_globals)^@  File "C:\Users\chenwei\AppData\Local\Programs\Python\Python37\Scripts\vimwiki_markdown.exe\__main__.py", line 7, in <module>^@  File "c:\users\chenwei\appdata\local\programs\python\python37\lib\site-packages\vimwiki_markdown.py", line 69, in main^@    TEMPLATE_EXT = sys.argv[9]^@IndexError: list index out of range^@
Vimwiki: HTML conversion is done, output: d:\WeirdData\VimwikiMd\site_html\
```

What should I do ?

**Comment by arozehnal** [comment]
I have same trouble ...

OS: Windows 10
Vim 8.2, VimwikiShowVersion: 2.5

c:\Users\ro\vimwiki>python -m pip list | grep vimwiki-markdown
vimwiki-markdown              0.3.1

.vimrc
for the first attempt I used same same fragment which works for me on AIX
`let g:vimwiki_list = [{
      \ 'path': '~/vimwiki',
      \ 'template_path': '~/vimwiki/templates/',
      \ 'template_default': 'default',
      \ 'syntax': 'markdown',
      \ 'ext': '.md',
      \ 'path_html': '~/vimwiki/site_html/',
      \ 'custom_wiki2html': 'vimwiki_markdown',
      \ 'template_ext': '.tpl'}]
`
for the second attempt I used
`let g:vimwiki_list = [{
      \ 'path': 'c:\Users\ro\vimwiki',
      \ 'template_path': 'c:\Users\ro\vimwiki\templates\',
      \ 'template_default': 'default',
      \ 'syntax': 'markdown',
      \ 'ext': '.md',
      \ 'path_html': 'c:\Users\ro\vimwiki\site_html\',
      \ 'custom_wiki2html': 'vimwiki_markdown',
      \ 'template_ext': '.tpl'}]
`

Both attempts finished same:
![py_vimwiki_md](https://user-images.githubusercontent.com/8810398/98699997-00b76a00-2378-11eb-91bd-72b758e44e58.jpg)

Any suggestion?

**Comment by WnP** [comment]
Hi @VimWei @arozehnal,

I've just released a new version `0.3.2` which should fix this issue. Can you try it and give me some feedback? I don't have windows.

For the record the issue come from the fact that vimwiki doesn't send some arguments on windows, now you can defined those arguments using environment variable if you wish, but it's not mandatory, here are those ones:

- `TEMPLATE_PATH`: `VIMWIKI_TEMPLATE_PATH`
- `TEMPLATE_DEFAULT`: `VIMWIKI_TEMPLATE_DEFAULT`
- `TEMPLATE_EXT`: `VIMWIKI_TEMPLATE_EXT`
- `ROOT_PATH`: `VIMWIKI_ROOT_PATH`

**Comment by WnP** [comment]
Those environment variables are now documented:

https://github.com/WnP/vimwiki_markdown#environment-variables

**Comment by WnP** [comment]
feel free to re-open this issue if needed.

**Comment by VimWei** [comment]
Thanks for update.   It didn't fix the issue:

```
"index.md" [unix] 87L, 2615B written
Traceback (most recent call last):^@  File "c:\users\chenwei\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main^@    return _run_code(code, main_globals, None,^@  File "c:\users\chenwei\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code^@    exec(code, run_globals)^@  File "C:\Users\chenwei\AppData\Local\Programs\Python\Python38\Scripts\vimwiki_markdown.exe\__main__.py", line 7, in <module>^@  File "c:\users\chenwei\appdata\local\programs\python\python38\lib\site-packages\vimwiki_markdown.py", line 107, in main^@    with open(INPUT_FILE, "rb") as f:^@FileNotFoundError: [Errno 2] No such file or directory: 'default'^@
Vimwiki: HTML conversion is done, output: d:\WeirdData\VimwikiMd\site_html\
```

**Comment by levirs565** [comment]
> Thanks for update. It didn't fix the issue:
> 
> ```
> "index.md" [unix] 87L, 2615B written
> Traceback (most recent call last):^@  File "c:\users\chenwei\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main^@    return _run_code(code, main_globals, None,^@  File "c:\users\chenwei\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code^@    exec(code, run_globals)^@  File "C:\Users\chenwei\AppData\Local\Programs\Python\Python38\Scripts\vimwiki_markdown.exe\__main__.py", line 7, in <module>^@  File "c:\users\chenwei\appdata\local\programs\python\python38\lib\site-packages\vimwiki_markdown.py", line 107, in main^@    with open(INPUT_FILE, "rb") as f:^@FileNotFoundError: [Errno 2] No such file or directory: 'default'^@
> Vimwiki: HTML conversion is done, output: d:\WeirdData\VimwikiMd\site_html\
> ```

I have same problem and i have solution for this problem. This is not vimwiki_markdown bug. But **it is vimwiki bug**. I have been creating patch for this vimwiki bug. This is [my patch](https://github.com/vimwiki/vimwiki/pull/1057/). This patch should fix your issue

**Comment by WnP** [comment]
Thanks @levirs565 for pointing this out.

@VimWei let me know if it fix this issue for you, in which case I think we can close this issue.

**Comment by VimWei** [comment]
Thank! It works!
