### ISSUE TITLE
'\' before special characters in math mode go missing

### ISSUE THREAD

**Issue by jlbosse** [WnP/vimwiki_markdown#8]
Somehow the conversion misses backslashes `\` that are in front of other special characters, like e.g. `\` or `{` when in math mode. This means that things 
like new lines `\\` or `\left\{` don't work in math mode.

**Expected behaviour**

```markdown
A lot of text

$$
\begin{aligned}
H &= A \\
   &= \left\{B \right\}
\end{aligned}
$$

more text
```

gets converted to 

```html
<p>A lot of text </p>
<p>$$
\begin{aligned}
H &= A \\
   &= \left\{B \right\}
\end{aligned}
$$</p>
<p>more text </p>
```

**Actual behaviour**

It gets converted to 

```html
<p>A lot of text </p>
<p>$$
\begin{aligned}
H &= A \
   &= \left{B \right}
\end{aligned}
$$</p>

<p>more text </p>
```

**Comment by jakobkogler** [comment]
Already mentioned it in #14 
You can fix it by installing the `markdown_math_escape` plugin with `pip` (`pip install markdown_math_escape`), and enable it by setting the environment variable for the additional markdown extensions: `export VIMWIKI_MARKDOWN_EXTENSIONS=markdown_math_escape`

**Comment by WnP** [comment]
I'm closing this issue, see #14 and @jakobkogler comment.
